[project]
name = "dotfiles"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rinsuki", email = "428rinsuki+git@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "tomlkit>=0.15.1",
]

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"

[tool.uv]
package = false
