#!/usr/bin/env python3
import subprocess
import sys
import os
mountpoints = [
    ["/Users/user/Desktop/work", sys.argv[1] if len(sys.argv) >= 2 else "/home/user/work"]
]
cwd = os.getcwd()
point = None
for local_point, dev_point in mountpoints:
    if cwd.startswith(local_point):
        point = dev_point + cwd.replace(local_point, "")
if point == None:
    print("Error: not mount point",file=sys.stderr)
    exit(1)
print(point)